steps:
- id: docker-pull
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - docker pull asia.gcr.io/$PROJECT_ID/go-devenv:latest || exit 0

- id: docker-build
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t=asia.gcr.io/$PROJECT_ID/go-devenv:latest
  - --cache-from=asia.gcr.io/$PROJECT_ID/go-devenv:latest
  - .
  #
- id: docker-push
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - asia.gcr.io/$PROJECT_ID/go-devenv:latest

timeout: 1200s
images:
- asia.gcr.io/$PROJECT_ID/go-devenv:latest

